use shopping_trend;
--------------
-- ANALYSIS --
--------------
-- How many customers have shown up and what is the total revenue generated by them ?
select count(distinct customer_id) as total_customers, sum(purchase_amount_usd) as total_revenue
from shopping_trends;
-- Around 3900 customers have shown up and made a revenue of $233081 according to the given dataset

-- should the stock store more male or female clothing ?
select gender, count(*) as gender_count, round(count(*)*100/(select count(*) from shopping_trends)) as percentage
from shopping_trends
group by 1;
-- Male Customers are much more in comparison to female ones comprising over 68% of total customers 

-- What is the average spent and total revenue from each gender ?
select gender, count(*) as customers, avg(purchase_amount_usd) as average_spent, sum(purchase_amount_usd) as total_revenue 
from shopping_trends
group by 1;
-- Males have generated more revenue as compared to females but on an average, females have spent slightly more

-- What is the average money spent on purchases by different age groups ?
select 
  case 
    when age between 18 and 25 then '18-25'
    when age between 26 and 35 then '26-35'
    when age between 36 and 45 then '36-45'
    when age between 46 and 55 then '46-55'
    else '56+'
  end as age_group, count(*) as customers, avg(purchase_amount_usd) as average_spent
from shopping_trends
group by 1 
order by 3 desc;
-- 18-25 age group customers have recorded the maximum average money spent being $60.65 while the minimum average money spent was $59.06 from customers who are 56+

-- Which 10 items generate the highest sales ?
select item_purchased,sum(purchase_amount_usd) as total_sales
from shopping_trends
group by 1
order by 2 desc
limit 10;
-- Blouse, Shirt, Dress, Pants, Jewelry, Sunglasses, Belt, Scarf, Sweater and Shorts are the items generating the highest sales

-- What are the 10 most purchased items ?
select item_purchased, count(*) as purchases
from shopping_trends
group by 1 
order by 2 desc
limit 10;
-- Blouse,Jewelry,Pants,Shirt,Dress,Sweater,Jacket,Belt,Sunglasses and Coats were among the top 10 most purchased items

-- How will you rank the items within each season based on the number of times they are purchased and show what is the top ranked item within each season ?
select season, item_purchased, purchase_count
from (select season, item_purchased, count(*) as purchase_count, dense_rank()over(partition by season order by count(*) desc) as ranking
      from shopping_trends
      group by 1,2
      order by 3 desc) as ranked_items
where ranking=1;
-- Jackets were most sold in fall followed by Sunglasses in winters, sweaters in spring and Pants in summers

-- How will you give rankings to items based on customer experience and extract top 10 rankings ?
select*
from (select item_purchased, round(avg(review_rating),3) as rating, dense_rank()over(order by round(avg(review_rating),3) desc) as ranking
       from shopping_trends
	   group by 1) as ranked_items
where ranking<=10;
-- Customers were most satisfied with items like Gloves, Sandals, Boots, Hat, T-shirt, Skirt, Handbag, Sweater, Jackets and Belts

-- How much revenue each category is generating ?
select category, sum(purchase_amount_usd) as total_revenue
from shopping_trends
group by 1 
order by 2 desc;
-- Clothing generates the highest revenue of $104264 followed by Accesories,Footwear, and Outerwear generating 74200,36093 and 18524 USD respectively

-- Rank the categories within each season based on the revenue they are generating and show what are the 2 topmost ranked categories within each season ?
select season, category, revenue
from (select season, category, sum(purchase_amount_usd) as revenue, dense_rank()over(partition by season order by sum(purchase_amount_usd) desc) as ranking
      from shopping_trends
      group by 1,2) as ranked_items
where ranking<=2;
-- Clothing is the most revenue generating category and the second most revenue generating category is Accessories in each season

-- How will you give rankings to categories based on customer experience ?
select category, round(avg(review_rating),3) as rating, dense_rank()over(order by round(avg(review_rating),3) desc) as ranking
from shopping_trends
group by 1;
-- The customers on account of average were most satisfied purchasing in categories going from Footwear to Accessories, to Outerwear and then Clothing
       
-- What are the top 5 locations in which most purchases have been made ?
select location, count(customer_id) as purchases
from shopping_trends
group by 1 
order by 2 desc
limit 5;
-- Most purchases were made in Montana followed by California, Idaho, Illinois, and then Alabama

-- Which 10 locations have generated the most revenue ?
select location, sum(purchase_amount_usd) as revenue
from shopping_trends
group by 1 
order by 2 desc
limit 10;
-- Most revenue is generated from Montana, Illinois, California, Idaho, Nevada, Alabama, New York, North Dakota, West Virginia and Nebraska

-- Which 10 locations are top performing in terms of customer experience ?
select location, round(avg(review_rating),2) as Avg_ratings
from shopping_trends
group by 1 
order by 2 desc
limit 10;
-- The top 10 locations based on customer experience were Texas, Wisconsin, Iowa, Maine, California, Michigan, Indiana, North Carolina, Montana and then Ohio

-- What are the 10 most preferred colors ?
select color, count(*) as preference
from shopping_trends
group by 1 
order by 2 desc
limit 10; 
-- The colors which were sold mostly were Olive, Yellow, Silver, Teal, Green, Black, Cyan, Violet, Gray and Maroon

-- Give the percentage of customers purchasing for different size categories and give the revenue generated by each size ?
select size, round((count(*)*100/(select count(*) from shopping_trends)),2) as percentage, sum(purchase_amount_usd) as revenue
from shopping_trends
group by 1 
order by 3 desc;
-- Around 45% of the customers have purchased medium size which generated a maximum revenue of $105167 . 
-- On the other hand, 11% of the customers have purchased in extra large size category which generated revenue of $25779 to be more precise

-- Who are the top 10 most loyal customers and what were thier most recent spending ?
select customer_id, purchase_amount_usd
from shopping_trends
where previous_purchases=(select max(previous_purchases) from shopping_trends) and frequency_of_purchases="Bi-weekly"
order by 2 desc
limit 10;
-- The customers with ID's being 1738, 2443, 1356, 3436, 2167, 102, 1953, 2908, 3743 and 1620 are the most loyal customers who spent the most in thier recent purchase

-- How much transactions have been done using different payment methods and what are the revenues generated by them ?
select payment_method, count(*) as total_transactions, sum(purchase_amount_usd) as total_revenue
from shopping_trends
group by 1
order by 3 desc;
-- Most transactions (671) were made by credit card and the revenue was $40310 whereas least transactions (612) were made through Bank transfer and its revenue was $36544